export const ADD_NEW_GROUP_REQUEST = "ADD_NEW_GROUP_REQUEST";
export const ADD_NEW_GROUP_SUCCSESS = "ADD_NEW_GROUP_SUCCSESS";
export const ADD_NEW_GROUP_FAILURE = "ADD_NEW_GROUP_FAILURE";

export const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST";
export const DELETE_GROUP_SUCCSESS = "DELETE_GROUP_SUCCSESS";
export const DELETE_GROUP_FAILURE = "DELETE_GROUP_FAILURE";

export const ADD_CUSTOMER_REQUEST = "ADD_CUSTOMER_REQUEST";
export const ADD_CUSTOMER_SUCCSESS = "ADD_CUSTOMER_SUCCSESS";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";

export const UPDATE_GROUP_REQUEST = "UPDATE_GROUP_REQUEST";
export const UPDATE_GROUP_SUCCSESS = "UPDATE_GROUP_SUCCSESS";
export const UPDATE_GROUP_FAILURE = "UPDATE_GROUP_FAILURE";

export const GET_SINGLE_CUSTOMER_REQUEST = "GET_SINGLE_CUSTOMER_REQUEST";
export const GET_SINGLE_CUSTOMER_SUCCSESS = "GET_SINGLE_CUSTOMER_SUCSESS";
export const GET_SINGLE_CUSTOMER_FAILURE = "GET_SINGLE_CUSTOMER_FAILURE";

export const GET_SINGLE_CUSTOMER_UPDATE_REQUEST =
  "GET_SINGLE_CUSTOMER_UPDATE_REQUEST";
export const GET_SINGLE_CUSTOMER_UPDATE_SUCCSESS =
  "GET_SINGLE_CUSTOMER_UPDATE_SUCSESS";
export const GET_SINGLE_CUSTOMER_UPDATE_FAILURE =
  "GET_SINGLE_CUSTOMER_UPDATE_FAILURE";
export const GET_SINGLE_CUSTOMER_UPDATE_RESET =
  "GET_SINGLE_CUSTOMER_UPDATE_RESET";

export const SEARCH_CUSTOMER_REQUEST = "SEARCH_CUSTOMER_REQUEST";
export const SEARCH_CUSTOMER_SUCCSESS = "SEARCH_CUSTOMER_SUCCSESS";
export const SEARCH_CUSTOMER_FAILURE = "SEARCH_CUSTOMER_FAILURE";
export const SEARCH_CUSTOMER_RESET = "SEARCH_CUSTOMER_RESET";
